### ISSUE TITLE
Spezifikationen/"Lastenheft"

### ISSUE THREAD

**Issue by ChrBeringer** [RG-Advanced-Water-Technologies/VaporVolumeValueFinder#9]
Mindestanforderungen:

Priorität 1:
- [ ] Ausgabe der gefundenen Peakwerte (x-Werte): 1.) Peakmitte, 2.) Peakanfang und -Peakende im mt-volav-File
- [ ] Ausgabe der einzelnen korrespondierenden xy-Wertepaare zwischen den Peak-x-Werten des mt-volav-File im VaporVolume-File
- [ ] Ausgabe eines sinnvollen Mittelwertes der vaporvolume-Wertepaare aus dem VaporVolume-Diagramm zwischen den ermittelten Peaks

Priorität 2:
- [ ] Grafische Darstellung der gefundenen Peaks im mt-volav-File
- [ ] Grafische Darstellung der gemittelten Bereiche im VaporVolumeFile

Hinreichende Anforderungen:
- [ ] Ausgabe der Reaktorgeometrien auf Basis des Dateinamens
- [ ] Abspeichern der Daten: Reaktorgeometrie, VaporVolume, mt-volav-Peaks

**Comment by ChrBeringer** [comment]
@BaconBeaver: Passt das so?

**Comment by BaconBeaver** [comment]
Ja, tiptop
